name: black
on: pull_request
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v1
        with:
          python-version: 3.12.8
      - run: pip install black
      - run: |
          black --check .
